GET http://localhost:3001/api/blogs


###
GET http://localhost:3001/api/blogs?search=sandesh


###
GET http://localhost:3001/api/blogs/6



###
POST http://localhost:3001/api/blogs
Authorization: Bearer
content-type: application/json

{
  "author": "Sajani Karmacharya",
  "url": "http://sajani-karmacharya.com",
  "title": "Sajani second blog",
  "likes": 5,
  "year": "2022"
}

###
PUT http://localhost:3001/api/blogs/2
Content-Type: application/json
 Authorization: Bearer

{
  "likes": "55"
}


###
DELETE http://localhost:3001/api/blogs/7
Authorization: Bearer