POST http://localhost:3001/api/readinglists
Content-Type: application/json

{
  "blogId": "2",
  "userId": "2"
}

###
PUT http://localhost:3001/api/readinglists/2
Content-Type: application/json
Authorization: Bearer


{
  "read": "true"
}