GET http://localhost:3001/api/users




###
GET http://localhost:3001/api/users/2?read=true



###
POST http://localhost:3001/api/users
content-type: application/json

{
  "name": "Sandesh Hyoju",
  "username": "sundesz@gmail.com",
  "password": "sandesh"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "sundesz@gmail.com",
  "password": "sandesh"
}

###
DELETE http://localhost:3001/api/logout
Authorization: Bearer


###
PUT http://localhost:3001/api/users
Content-Type: application/json
Authorization: Bearer

{
  "userId": 1,
  "disabled": false
}
