GET http://localhost:3001/api/blogs


###
GET http://localhost:3001/api/blogs/1


###
POST http://localhost:3001/api/blogs
content-type: application/json

{
  "author": "Sajani Karmacharya",
  "url": "http://sajani-karmacharya.com",
  "title": "Sajani Blog",
  "likes": 15
}

###
PUT http://localhost:3001/api/blogs/2
Content-Type: application/json

{
  "likes": 5
}


###
DELETE http://localhost:3001/api/blogs/2